### ISSUE TITLE
Nothing working with IE11!!!

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-core#125]
Are you aware that noone of your demo pages (actually I tried vaadin-grid and vaadin-combobox) actually works with IE11? (And there are problems also on the documentation pages?)
What you get is a high CPU activity for some seconds, and then in the console all sort of errors, repeated many many times.
Since at the moment I cannot have my polymer (2) application working in IE11 (also using vaadin components, but it's accidental, of course), I was wondering if there can be some relation between the two things...
I have to deliver my application before the end of July, and IE11 is not a choice... I have to support it!
Do you have some good advice on this? What would you do???
Thanks for every thought you would like to share...
P.S.: there is a recognized bug on the polymer 2 CLI, where I posted my experience: https://github.com/Polymer/polymer-cli/issues/779
Even if the errors I get for your demos are different!

**Comment by jouni** [comment]
@andreabioli, do you still have issues with IE11? Also, some of the issues could be caused by the polyfills, as has been discussed recently in the Polymer community: 
https://github.com/Polymer/polymer/issues/4787
https://github.com/webcomponents/shadydom/issues/168

**Comment by jouni** [comment]
Also, we deployed a new version of our website a week ago, so now would be a great time to check those out with IE11 and report any issues there still might be.

**Comment by limonte** [comment]
> Also, we deployed a new version of our website a week ago, so now would be a great time to check those out with IE11 and report any issues there still might be.

Still the same issue which can be described as "Nothing working with IE11!!!"

![](https://i.imgur.com/Yb55fFp.png)

**Comment by web-padawan** [comment]
BTW `shadydom` 1.0.5 was recently released with the fix for [webcomponents/shadydom#168](https://github.com/webcomponents/shadydom/issues/168).

**Comment by manolo** [comment]
Almost our demos are using ES6, hence they need to be transpiled before they can be used in IE11. 
Since we are loading the snippets via a pure P2 component that reads the javascript payload and executes it, It might be a problem to consider.

**Comment by samiheikki** [comment]
Should be fixed nowadays right?

**Comment by jouni** [comment]
Closing. This issue is too broad in scope to be actionable, and we don’t have real indications that the components wouldn’t work in IE11.
